# -*- coding: utf-8 -*-
"""GenAI-6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nNYlE-3-4gIPZC40YQro2Z3jgReUclC2
"""

# Commented out IPython magic to ensure Python compatibility.
# %pip install --upgrade --quiet huggingface_hub
# %pip install --upgrade langchain

from transformers import pipeline
sentiment_analyzer = pipeline("sentiment-analysis")
sentences = [
  "The product quality is amazing! I'm very satisfied.",
  "I had a terrible experience with customer service.",
  "The delivery was quick, but the packaging was damaged.",
]
results = sentiment_analyzer(sentences)
for sentence, result in zip(sentences, results):
  print(f"Sentence: {sentence}\nSentiment: {result['label']}, Confidence: {result['score']:.2f}\n")